[patch.crates-io]
proc-macro2 = "=1.0.79"
quote = "=1.0.26"
syn = "=1.0.109"

[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
idl-build = ["anchor-spl/idl-build"]
resolution = true
skip-lint = false

[programs.localnet]
lending = "B7eNrb1uJR9risFgqTQhnxKQt18itfVdoz4XYufEAEX8"
marketplace = "9B1oveu4aVQjxboVRa4FYB9iqtbBoQhHy9FNrKNzSM8c"

[programs.devnet]
lending = "B7eNrb1uJR9risFgqTQhnxKQt18itfVdoz4XYufEAEX8"
marketplace = "9B1oveu4aVQjxboVRa4FYB9iqtbBoQhHy9FNrKNzSM8c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/new-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
