[patch.crates-io]
proc-macro2 = "=1.0.79"
quote = "=1.0.26"
syn = "=1.0.109"

[toolchain]
package_manager = "yarn"

[features]
idl-build = ["anchor-spl/idl-build"]
resolution = true
skip-lint = false

[programs.localnet]
contract = "4WC4MDgPpPW3PY4idJT5ffX1NJpkYhLfRv2sDUsGCWLa"
lending = "2g7jcHp3Kxybhtp2rkAVhqRn5YscGyJP3FGUMZ5G8vVE"

[programs.devnet]
contract = "4WC4MDgPpPW3PY4idJT5ffX1NJpkYhLfRv2sDUsGCWLa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
