/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExploreHomeIndexImport } from './routes/explore/home/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExploreHomeIndexRoute = ExploreHomeIndexImport.update({
  id: '/explore/home/',
  path: '/explore/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore/home/': {
      id: '/explore/home/'
      path: '/explore/home'
      fullPath: '/explore/home'
      preLoaderRoute: typeof ExploreHomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore/home': typeof ExploreHomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore/home': typeof ExploreHomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/explore/home/': typeof ExploreHomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore/home'
  id: '__root__' | '/' | '/explore/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreHomeIndexRoute: typeof ExploreHomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreHomeIndexRoute: ExploreHomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/explore/home/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/explore/home/": {
      "filePath": "explore/home/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
